
server:
  port: 8080

spring:
  application:
    name: bff-service

user:
  service:
    url: http://localhost:8081

order:
  service:
    url: http://localhost:8082

logging:
  level:
    com.example.bffservice: DEBUG
    org.springframework.web.client: DEBUG